### ISSUE TITLE
Quickstart Issue: Exception thrown with KeyError '0'

### ISSUE THREAD

**Issue by newfront** [delta-io/delta-docs#44]
Where the Bug was found: Location: https://github.com/delta-io/delta-docs/blob/main/static/quickstart_docker/README.md

The quickstart_docker/README.md example raises an exception when testing out the python writer.

## Exception
~~~
>>> df = pd.DataFrame(range(5))
>>> write_deltalake("/tmp/deltars_table", df)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyarrow/pandas_compat.py", line 428, in _get_columns_to_convert_given_schema
    col = df[name]
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/range.py", line 395, in get_loc
    raise KeyError(key)
KeyError: '0'
~~~

## Fix
Adding a column name fixes the issue. 
~~~
>>> df = pd.DataFrame( {"data": range(5)} )
>>> write_deltalake("/tmp/deltars_table", df)
~~~

**Comment by newfront** [comment]
My environment: 
Docker Engine: v20.10.23
OS: MacOS Ventura 13.2.1
Chip: M1 Max

**Comment by newfront** [comment]
Note: pip3 list from the built docker instance.

```
NBuser@93574139d761:/opt/spark/work-dir$ pip3 list
Package                  Version  
------------------------ ---------
aiofiles                 22.1.0   
aiosqlite                0.18.0   
anyio                    3.6.2    
argon2-cffi              21.3.0   
argon2-cffi-bindings     21.2.0   
asttokens                2.2.1    
attrs                    22.2.0   
Babel                    2.12.1   
backcall                 0.2.0    
beautifulsoup4           4.12.0   
bleach                   6.0.0    
certifi                  2022.12.7
cffi                     1.15.1   
charset-normalizer       3.1.0    
comm                     0.1.3    
debugpy                  1.6.6    
decorator                5.1.1    
defusedxml               0.7.1    
delta-spark              2.1.0    
deltalake                0.8.1    
executing                1.2.0    
fastjsonschema           2.16.3   
idna                     3.4      
importlib-metadata       6.1.0    
importlib-resources      5.12.0   
ipykernel                6.22.0   
ipython                  8.11.0   
ipython-genutils         0.2.0    
jedi                     0.18.2   
Jinja2                   3.1.2    
json5                    0.9.11   
jsonschema               4.17.3   
jupyter-client           8.1.0    
jupyter-core             5.3.0    
jupyter-events           0.6.3    
jupyter-server           2.5.0    
jupyter-server-fileid    0.8.0    
jupyter-server-terminals 0.4.4    
jupyter-server-ydoc      0.8.0    
jupyter-ydoc             0.2.3    
jupyterlab               3.6.2    
jupyterlab-pygments      0.2.2    
jupyterlab-server        2.21.0   
MarkupSafe               2.1.2    
matplotlib-inline        0.1.6    
mistune                  2.0.5    
nbclassic                0.5.3    
nbclient                 0.7.2    
nbconvert                7.2.10   
nbformat                 5.8.0    
nest-asyncio             1.5.6    
notebook                 6.5.3    
notebook-shim            0.2.2    
numpy                    1.24.2   
packaging                23.0     
pandas                   1.5.3    
pandocfilters            1.5.0    
parso                    0.8.3    
pexpect                  4.8.0    
pickleshare              0.7.5    
pip                      20.0.2   
pkgutil-resolve-name     1.3.10   
platformdirs             3.2.0    
prometheus-client        0.16.0   
prompt-toolkit           3.0.38   
psutil                   5.9.4    
ptyprocess               0.7.0    
pure-eval                0.2.2    
py4j                     0.10.9.5 
pyarrow                  11.0.0   
pycparser                2.21     
Pygments                 2.14.0   
pyrsistent               0.19.3   
pyspark                  3.3.2    
python-dateutil          2.8.2    
python-json-logger       2.0.7    
pytz                     2023.3   
PyYAML                   6.0      
pyzmq                    25.0.2   
requests                 2.28.2   
rfc3339-validator        0.1.4    
rfc3986-validator        0.1.1    
roapi                    0.9.0    
Send2Trash               1.8.0    
setuptools               45.2.0   
six                      1.16.0   
sniffio                  1.3.0    
soupsieve                2.4      
stack-data               0.6.2    
terminado                0.17.1   
tinycss2                 1.2.1    
tomli                    2.0.1    
tornado                  6.2      
traitlets                5.9.0    
urllib3                  1.26.15  
wcwidth                  0.2.6    
webencodings             0.5.1    
websocket-client         1.5.1    
wheel                    0.34.2   
y-py                     0.5.9    
ypy-websocket            0.8.4    
zipp                     3.15.0 
```

Current Version of the delta-docs code base: 

```
> delta-docs % git log
commit 9798f5e8a1efe586e5b0fb63e803842a45265b8b (HEAD -> main, origin/main, origin/HEAD)
Author: Andrew Bauman <baumanab@gmail.com>
Date:   Fri Dec 23 11:03:05 2022 -0800

    Update roapi instructions: (#25)
```
